config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :categories
  resources :recipes
  resources :users
  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredient_recipes
  has_many :ingredients, through: :ingredient_recipes
  has_many :users, through: :ingredients
  has_many :recipe_categories
  has_many :categories, through: :recipe_categories
  validates :name, presence:true, uniqueness:true

  #NEEDS REFACTORING
  #maybe have it return an array of ingredients and categories needed for a recipe
  def print_ingredients
    pastel = Pastel.new
    puts pastel.red.underline("Ingredient(s) needed for #{self.name}")
    self.ingredient_recipes.each do |recipe_ingredient|
      if recipe_ingredient.ingredient == nil
        ingredient = "Any #{recipe_ingredient.category.name}"
      else
        ingredient = recipe_ingredient.ingredient.name
      end
      puts ingredient
    end
  end


  #check to see if this works
  #might not need these
  def general_ingredient_recipes
    self.ingredient_recipes.select {|ingredient_recipe| ingredient_recipe.ingredient == nil}
  end

  def specific_ingredient_recipes
    self.ingredient_recipes.select {|ingredient_recipe| ingredient_recipe.ingredient != nil}
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def show
    find_recipe
  end

  def edit
    find_recipe
  end

  def update
    find_recipe
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :calories, :duration, :image_url)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
  <% @recipe.errors.full_messages.each do |msg| %>
    <%= msg %><br>
  <% end %>
<% end %>

<%= form_for @recipe do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :duration %><br>
  <%= f.number_field :duration %><br>
  <%= f.label :calories %><br>
  <%= f.number_field :calories %><br>
  <%= f.label :image_url %><br>
  <%= f.text_field :image_url %><br>
  <%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit <%= @recipe.name %></h1>
<%= render "form" %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %></li>  
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<%= button_to "Back to Recipes", recipes_path, method: :get %>