config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :categories
  resources :recipes
  resources :users
  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredient_users
  has_many :users, through: :ingredient_users
  has_many :ingredient_recipes
  has_many :recipes, through: :ingredient_recipes
  has_many :ingredient_categories
  has_many :categories, through: :ingredient_categories
  validates :name, presence:true, uniqueness:true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to @ingredient
    else
      render :new
    end
  end

  def show
    find_ingredient
  end

  def edit
    find_ingredient
  end

  def update
    find_ingredient
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def find_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :calories, :hearts, :cooked_effect, :image_url)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<% if @ingredient.errors.any? %>
  <% @ingredient.errors.full_messages.each do |msg| %>
    <%= msg %><br>
  <% end %>
<% end %>

<%= form_for @ingredient do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :calories%><br>
  <%= f.number_field :calories %><br>
  <%= f.label :hearts %><br>
  <%= f.number_field :hearts %><br>
  <%= f.label :cooked_effect %><br>
  <%= f.text_field :cooked_effect %><br>
  <%= f.label :image_url %><br>
  <%= f.text_field :image_url %><br>
  <%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit <%= @ingredient.name %></h1>
<%= render "form" %>

app/views/ingredients/index.html.erb
<h1>All Ingredients</h1>
<ul>
  <% @ingredients.each do |ingredient| %>
    <li><%= link_to ingredient.name, ingredient %></li>  
  <% end %>
</ul>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render "form" %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>
<%= button_to "Back to Ingredients", ingredients_path, method: :get %>