config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :categories
  resources :recipes
  resources :users
  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ingredient_categories
  has_many :ingredients, through: :ingredient_categories
  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories

  validates :name, presence:true, uniqueness:true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def show
    find_category
  end

  def edit
    find_category
  end

  def update
    find_category
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |msg| %>
    <%= msg %><br>
  <% end %>
<% end %>

<%= form_for @category do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit <%= @category.name %></h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category %></li>  
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render "form" %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= button_to "Back to Categories", categories_path, method: :get %>